import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from 'react'
import axios from 'axios'
export default function Home() {
  let url=`http://localhost:3000/api/hello`
    const [name, setname] = React.useState("");
    const ritesh = async()=>{
       
      let {data}=await axios.post(url,{name:name}) 
       
      if(data.status===true){
        window.location.href='/home'
      }else{
        alert("Loggin false")
      }
    }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <input type="text" placeholder='Name'
        onChange={(e)=>{
          setname(e.target.value)
        }}
      />
      <input type="text" placeholder='password' />
      <button type='submit' 
      onClick={ritesh}
      > submit</button>
    </div>
  )
}
